### ISSUE TITLE
Command string generated from "Add a New Device" dialog does not activate a machine.

### ISSUE THREAD

**Issue by Walt-Intel** [open-amt-cloud-toolkit/ui-toolkit#451]
**Describe the bug** 🪲
The command string generated to activate a linux machine or a windows machine generates an error message.

**To Reproduce** 🪜
Steps to reproduce the behavior on a linux machine:
1. Go to 'https://192.168.1.153/devices'
2. Click on '+ Add a Device.'
3. Select your profile and click 'Linux'
4. Copy the command generated to the linux command prompt
5. rtc generates the following error message:
```
localhost rpc-go]$ sudo ./rpc -u wss://192.168.1.153/activate -n -c '-t activate --profile AlphaProfile' 
[sudo] password for rbhe-vyshali: 

Remote Provisioning Client (RPC) - used for activation, deactivation, and status of AMT

Usage: rpc COMMAND [OPTIONS]

Supported Commands:
  activate    Activate this device with a specified profile
              Example: ./rpc activate -u wss://server/activate --profile acmprofile
  deactivate  Deactivates this device. AMT password is required
              Example: ./rpc deactivate -u wss://server/activate
  maintenance Maintain this device.
              Example: ./rpc maintenance -u wss://server/activate
  amtinfo     Displays information about AMT status and configuration
              Example: ./rpc amtinfo
  version     Displays the current version of RPC and the RPC Protocol version
              Example: ./rpc version

Run 'rpc COMMAND' for more information on a command.
```

**Expected behavior**
The device should have been activated.

**Screenshots** 🖼️

**Browser Information (please complete the following information):** 🖥️
 - OS: CentOS 8 (Linux localhost.localdomain 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
 - OS: Windows 11 Pro 10.0.22000 Build 22000
 - Browser and Version: Brave

**Additional context**

**Comment by rsdmike** [comment]
fixed in https://github.com/open-amt-cloud-toolkit/sample-web-ui/pull/587
