### ISSUE TITLE
How to use the UI Toolkit to directly connect to AMT device (without using MPS)?

### ISSUE THREAD

**Issue by rgl** [open-amt-cloud-toolkit/ui-toolkit#517]
Is there a way to use the UI Toolkit to directly connect to AMT device without MPS?

It seems that https://github.com/open-amt-cloud-toolkit/ui-toolkit/blob/main/src/core/AMTRedirector.ts is handling all the communication for the UI, is there a mock/light/simple server implementation that directly connects to the AMT device?

**Comment by rjbrache** [comment]
Currently the toolkit UI only supports connections to AMT via CIRA, which requires MPS.  If you want a direct connection, you can use the toolkit (RPS and RPC) to configure AMT with a TLS configuration and use something like Mesh Commander as your UI.
